services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: user_management_system
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  backend:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ../shared:/usr/src/app/shared
    command: npm run dev
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
